export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';
export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';

export const BUS_VIEW_BOOKING_ERROR = 'BUS_VIEW_BOOKING_ERROR';
export const BUS_VIEW_BOOKING_SUCCESS = 'BUS_VIEW_BOOKING_SUCCESS';
export const BUS_VIEW_BOOKING_REQUEST = 'BUS_VIEW_BOOKING_REQUEST';

export const BUS_BOOKING_LIST_ERROR = 'BUS_BOOKING_LIST_ERROR';
export const BUS_BOOKING_LIST_SUCCESS = 'BUS_BOOKING_LIST_SUCCESS';
export const BUS_BOOKING_LIST_REQUEST = 'BUS_BOOKING_LIST_REQUEST';

export const BUS_TYPE_LIST_ERROR = 'BUS_TYPE_LIST_ERROR';
export const BUS_TYPE_LIST_SUCCESS = 'BUS_TYPE_LIST_SUCCESS';
export const BUS_TYPE_LIST_REQUEST = 'BUS_TYPE_LIST_REQUEST';

export const BUS_OPERATORS_LIST_ERROR = 'BUS_OPERATORS_LIST_ERROR';
export const BUS_OPERATORS_LIST_SUCCESS = 'BUS_OPERATORS_LIST_SUCCESS';
export const BUS_OPERATORS_LIST_REQUEST = 'BUS_OPERATORS_LIST_REQUEST';

export const BUS_CONFIRM_DETAILS_LIST_ERROR = 'BUS_CONFIRM_DETAILS_LIST_ERROR';
export const BUS_CONFIRM_DETAILS_LIST_SUCCESS = 'BUS_CONFIRM_DETAILS_LIST_SUCCESS';
export const BUS_CONFIRM_DETAILS_LIST_REQUEST = 'BUS_CONFIRM_DETAILS_LIST_REQUEST';

export const BUS_SEARCH_LIST_SUCCESS = 'BUS_SEARCH_LIST_SUCCESS';
export const BUS_SEARCH_LIST_ERROR = 'BUS_SEARCH_LIST_ERROR';
export const BUS_SEARCH_LIST_REQUEST = 'BUS_SEARCH_LIST_REQUEST';

export const USER_PROFILE_UPDATE_ERROR = 'USER_PROFILE_UPDATE_ERROR';
export const USER_PROFILE_UPDATE_SUCCESS = 'USER_PROFILE_UPDATE_SUCCESS';
export const USER_PROFILE_UPDATE_REQUEST = 'USER_PROFILE_UPDATE_REQUEST';

export const USER_ADD_CARD_ERROR = 'USER_ADD_CARD_ERROR';
export const USER_ADD_CARD_SUCCESS = 'USER_ADD_CARD_SUCCESS';
export const USER_ADD_CARD_REQUEST = 'USER_ADD_CARD_REQUEST';

export const USER_CARD_LIST_ERROR = 'USER_CARD_LIST_ERROR';
export const USER_CARD_LIST_SUCCESS = 'USER_CARD_LIST_SUCCESS';
export const USER_CARD_LIST_REQUEST = 'USER_CARD_LIST_REQUEST';

export const USER_CARD_DELETE_ERROR = 'USER_CARD_DELETE_ERROR';
export const USER_CARD_DELETE_SUCCESS = 'USER_CARD_DELETE_SUCCESS';
export const USER_CARD_DELETE_REQUEST = 'USER_CARD_DELETE_REQUEST';

export const BUS_BOOKING_ORDER_LIST_ERROR = 'BUS_BOOKING_ORDER_LIST_ERROR';
export const BUS_BOOKING_ORDER_LIST_SUCCESS = 'BUS_BOOKING_ORDER_LIST_SUCCESS';
export const BUS_BOOKING_ORDER_LIST_REQUEST = 'BUS_BOOKING_ORDER_LIST_REQUEST';

export const USER_EDIT_CARD_LIST_ERROR = 'USER_EDIT_CARD_LIST_ERROR';
export const USER_EDIT_CARD_LIST_SUCCESS = 'USER_EDIT_CARD_LIST_SUCCESS';
export const USER_EDIT_CARD_LIST_REQUEST = 'USER_EDIT_CARD_LIST_REQUEST';

export const USER_CHANGE_PASSWORD_ERROR = 'USER_CHANGE_PASSWORD_ERROR';
export const USER_CHANGE_PASSWORD_SUCCESS = 'USER_CHANGE_PASSWORD_SUCCESS';
export const USER_CHANGE_PASSWORD_REQUEST = 'USER_CHANGE_PASSWORD_REQUEST';